### PR TITLE
Stop suggesting use of xunit ThrowAsync for synchronous calls

### LINKED ISSUE #61: VSTHRD103 recommends xunit ThrowsAsync in async method
Because xunit's `Assert` class offers both `Throws` and `ThrowsAsync`, VSTHRD103 will claim an async test method should call the async version, when of course that is only appropriate if the delegate passed to the method is itself async.

```csharp
    [Fact]
    public async Task ReadByte_ReturnsMinus1AtEndOfStream()
    {
        this.bufferingStream = new MemoryStream();
        Assert.Throws<InvalidOperationException>(() => this.bufferingStream.ReadByte());
    }
```

### PR DESCRIPTION
**Pull request by AArnott**
Fixes #61

### CODE REVIEW

File: src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD103UseAsyncOptionAnalyzer.cs [hunk 1]
```diff
@@ -120,6 +123,19 @@ internal void AnalyzeInvocation(SyntaxNodeAnalysisContext context)
...
+            /// Determines whether the given method has parameters to cover all the parameter types in another method.
+            /// </summary>
+            /// <param name="candidateMethod">The candidate method.</param>
+            /// <param name="baselineMethod">The baseline method.</param>
+            /// <returns>
+            ///   <c>true</c> if <paramref name="candidateMethod"/> has a superset of parameter types found in <paramref name="baselineMethod"/>; otherwise <c>false</c>.
+            /// </returns>
+            private static bool HasSupersetOfParameterTypes(IMethodSymbol candidateMethod, IMethodSymbol baselineMethod)
+            {
+                return candidateMethod.Parameters.All(p => baselineMethod.Parameters.Any(pSync => pSync.Type?.Equals(p.Type) ?? false));
```
Comment (IlyaBiryukov) [inline src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD103UseAsyncOptionAnalyzer.cs]: pBaseline

Comment (AArnott) [inline src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD103UseAsyncOptionAnalyzer.cs]: Fixed
