### PR TITLE
Fix VSTHRD010 to fire on more IVs* scenarios

### LINKED ISSUE #65: VSTHRD010 doesn't fire for Microsoft.VisualStudio.OLE.Interop.IServiceProvider
VSTHRD010 doesn't fire for:
```
        public void TestMethodDoesntFire()
        {
            dynamic shell = ServiceProvider.GlobalProvider.GetService(typeof(Microsoft.VisualStudio.Shell.Interop.IVsShell));
            shell.something();
        }
        public object TestMethodDoesntFire2()
        {
            return (new object()) as Microsoft.VisualStudio.OLE.Interop.IServiceProvider;
        }
```

Though it correctly fires for:
```
        public void TestMethodDoesFire()
        {
            dynamic shell = ServiceProvider.GlobalProvider.GetService(typeof(IVsShell)) as MyCustomShell;
            shell.something();
        }
        public object TestMethodDoesFire2()
        {
            return (new object()) as Microsoft.VisualStudio.Shell.Interop.IVsShell;
        }

```

As an image:
image

The same issue happens for:
Microsoft.DiagnosticsHub.VisualStudio.SDK.IVsDiagnosticsHubService
and:
as Microsoft.DiagnosticsHub.IRecentListService

### PR DESCRIPTION
**Pull request by AArnott**
Fixes #65

### CODE REVIEW

File: src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD010VsServiceUsageAnalyzer.cs [hunk 1]
```diff
@@ -119,6 +119,7 @@ public override void Initialize(AnalysisContext context)
         private static bool IsVisualStudioShellInteropAssembly(string assemblyName)
         {
             return assemblyName.StartsWith("Microsoft.VisualStudio.Shell.Interop", StringComparison.OrdinalIgnoreCase)
+                || assemblyName.Equals("Microsoft.VisualStudio.OLE.Interop", StringComparison.OrdinalIgnoreCase)
```
Comment (digeff) [inline src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD010VsServiceUsageAnalyzer.cs]: Should this list contain all the Microsoft.VisualStudio.*.Interop assemblies?

I found these other assemblies too:
Microsoft.VisualStudio.WCFReference.Interop
Microsoft.VisualStudio.CodeAnalysis.Interop
Microsoft.VisualStudio.Converters.Interop
Microsoft.VisualStudio.Coverage.Interop
Microsoft.VisualStudio.Data.Interop
Microsoft.VisualStudio.DataTools.Interop
Microsoft.VisualStudio.Debugger.InteropA
Microsoft.VisualStudio.Debugger.Interop
Microsoft.VisualStudio.Debugger.SymbolLocator.Interop
Microsoft.VisualStudio.DesignTools.UwpInterop
Microsoft.VisualStudio.Platform.VSEditor.Interop
Microsoft.VisualStudio.Imaging.Interop
Microsoft.VisualStudio.Debugger.Interop
Microsoft.VisualStudio.TestTools.UITest.Extension.IE.Communication.Interop
Microsoft.VisualStudio.TextManager.Interop

Comment (AArnott) [inline src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD010VsServiceUsageAnalyzer.cs]: I don't know. I suspect not. The editor has free-threaded components. So I'd rather have a precise whitelist.
