### PR TITLE
Avoid compiler hang from invalid text in AdditionalFiles

### LINKED ISSUE #485: Trailing period in vs-threading.MembersRequiringMainThread.txt causes compiler hang
#### Bug description
The compiler entered a CPU intensive hang due to the `ReadTypesAndMembers` method in the vs-threading analyzers.

#### Repro steps
Add the content below to a file named `vs-threading.MembersRequiringMainThread.txt` that is supplied as an "AdditionalFile" to the compiler while the vs-threading analyzers are running on a project. Note the trailing period on the last line.

```
![Microsoft.VisualStudio.Shell.Interop.IVsAppContainerBootstrapper]
![Microsoft.VisualStudio.Shell.Interop.IVsAppContainerBootstrapper2]
![Microsoft.VisualStudio.Shell.Interop.IVsAppContainerBootstrapper3]
![Microsoft.VisualStudio.Shell.Interop.IVsAppContainerBootstrapper4]
![Microsoft.VisualStudio.Shell.Interop.IVsAppContainerBootstrapper5]
![Microsoft.VisualStudio.Shell.Interop.IVsAppContainerBootstrapper6]
![Microsoft.VisualStudio.Shell.Interop.IVsAppContainerProjectDeploy]
![Microsoft.VisualStudio.Shell.Interop.IVsAppContainerProjectDeploy2]
![Microsoft.VisualStudio.Shell.Interop.IVsAppContainerProjectDeployOperation]
![Microsoft.VisualStudio.Shell.Interop.IVsAppContainerProjectDeployResult]
![Microsoft.VisualStudio.Shell.Interop.IVsImmersiveProjectDeployTest]
![Microsoft.VisualStudio.Shell.Interop.SVsAppContainerProjectDeploy].
```

#### Expected behavior

The compiler completes. Maybe emits an error.

#### Actual behavior

The compiler hangs.

- Version used: 16.0.106

#### Additional context

@srdjanjovcic reported.

### PR DESCRIPTION
**Pull request by bluetarpmedia**
Added a timeout to `NegatableTypeOrMemberReferenceRegex` and `MemberReferenceRegex` to prevent a CPU hang when given input that causes (what I believe to be) very expensive regex backtracking.

Incidentally, some invalid input causes a hang but other invalid input just causes a no-match (as expected).

These cause a hang (or timeout when the Regex is given one):

```
![Microsoft.VisualStudio.Shell.Interop.SVsAppContainerProjectDeploy].   <-- original report

[Microsoft.VisualStud]FooBar
[Microsoft.VisualStudio]FooBar
[aaaaaaaaa.bbbbbbbbbb]FooBar                                            <-- 9 'a' then 10 'b'
```

But the following do not hang and instead return a Regex with no match (as expected).

```
[Microsoft.VisualStu]FooBar
[aaaaaaaaa.bbbbbbbbb]FooBar                                             <-- 9 'a' then 9 'b'
```

Maybe there's something internal to Regex which changes its implementation depending on the length of the input string?

Closes #485

### CODE REVIEW

File: src/Microsoft.VisualStudio.Threading.Analyzers/CommonInterest.cs [hunk 1]
```diff
@@ -84,8 +86,16 @@ internal static IEnumerable<TypeMatchSpec> ReadTypesAndMembers(AnalyzerOptions a
...
+                {
+                    match = NegatableTypeOrMemberReferenceRegex.Match(line);
+                }
+                catch (RegexMatchTimeoutException)
+                {
+                }
+
+                if (match == null || !match.Success)
                 {
                     throw new InvalidOperationException($"Parsing error on line: {line}");
```
Comment (AArnott) [inline src/Microsoft.VisualStudio.Threading.Analyzers/CommonInterest.cs:100]: I feel like we should report a timeout distinctly so folks realize it *could* just be that the computer was slow.

File: src/Microsoft.VisualStudio.Threading.Analyzers/CommonInterest.cs [hunk 2]
```diff
@@ -63,9 +63,11 @@ internal static class CommonInterest
 
         private const RegexOptions FileNamePatternRegexOptions = RegexOptions.IgnoreCase | RegexOptions.Singleline;
 
-        private static readonly Regex NegatableTypeOrMemberReferenceRegex = new Regex(@"^(?<negated>!)?\[(?<typeName>[^\[\]\:]+)+\](?:\:\:(?<memberName>\S+))?\s*$", RegexOptions.Singleline | RegexOptions.CultureInvariant);
+        private static readonly TimeSpan RegexMatchTimeout = TimeSpan.FromMilliseconds(100);  // Prevent expensive CPU hang in Regex.Match if backtracking occurs due to pathological input (see #485).
```
Comment (AArnott) [inline src/Microsoft.VisualStudio.Threading.Analyzers/CommonInterest.cs:66]: Timeouts this small seem very likely to misfire. We have "fast" tests with 3 second timeouts that still timeout occasionally, driving me to use nothing less than 5 second timeouts for anything that would report a failure rather than retry. Computers can just be slow sometimes.
```suggestion
        private static readonly TimeSpan RegexMatchTimeout = TimeSpan.FromSeconds(5);  // Prevent expensive CPU hang in Regex.Match if backtracking occurs due to pathological input (see #485).
```

**Review by AArnott — CHANGES_REQUESTED** [review]
Thank you for this. Just a couple touch-ups, please.

**Comment by AArnott** [comment]
@bluetarpmedia tip: Please use descriptive PR titles.

Not great:
image

Great:
image

You already use the magic `Closes #485` string in the PR description (which is great in other ways as well), so thank you for that.

File: src/Microsoft.VisualStudio.Threading.Analyzers/CommonInterest.cs (hunk 1 above)
Comment (bluetarpmedia) [reply src/Microsoft.VisualStudio.Threading.Analyzers/CommonInterest.cs:101]: Yeah, makes sense.

**Comment by bluetarpmedia** [comment]
> tip: Please use descriptive PR titles.

Will do, thanks!

**Review by AArnott — APPROVED** [review]
Thanks!

**Comment by bluetarpmedia** [comment]
Looks like the Linux job failed when restoring packages:

```
Restoring NuGet packages
  Determining projects to restore...
  Restored /home/vsts/work/1/s/src/Microsoft.VisualStudio.Threading/Microsoft.VisualStudio.Threading.csproj (in 6.69 sec).
  Restored /home/vsts/work/1/s/src/Microsoft.VisualStudio.Threading.Analyzers/Microsoft.VisualStudio.Threading.Analyzers.csproj (in 8.43 sec).
  Restored /home/vsts/work/1/s/src/Microsoft.VisualStudio.Threading.Analyzers.VisualBasic/Microsoft.VisualStudio.Threading.Analyzers.VisualBasic.csproj (in 942 ms).
  Restored /home/vsts/work/1/s/src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/Microsoft.VisualStudio.Threading.Analyzers.CSharp.csproj (in 180 ms).
  Restored /home/vsts/work/1/s/src/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes.csproj (in 793 ms).
  Restored /home/vsts/work/1/s/test/Microsoft.VisualStudio.Threading.Tests.Win7RegistryWatcher/Microsoft.VisualStudio.Threading.Tests.Win7RegistryWatcher.csproj (in 16 ms).
  Restored /home/vsts/work/1/s/test/Microsoft.VisualStudio.Threading.Tests/Microsoft.VisualStudio.Threading.Tests.csproj (in 4.55 sec).
  Restored /home/vsts/work/1/s/test/IsolatedTestHost/IsolatedTestHost.csproj (in 6 ms).
  Failed to download package 'Microsoft.VisualStudio.Imaging.Interop.14.0.DesignTime.16.11.31527.49' from 'https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/2a239fd0-3e21-40b0-b9d6-bc122fec7eb2/nuget/v3/flat2/microsoft.visualstudio.imaging.interop.14.0.designtime/16.11.31527.49/microsoft.visualstudio.imaging.interop.14.0.designtime.16.11.31527.49.nupkg'.
  Response status code does not indicate success: 503 (Service Unavailable).
  Failed to download package 'Microsoft.VisualStudio.Imaging.Interop.14.0.DesignTime.16.11.31527.49' from 'https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/2a239fd0-3e21-40b0-b9d6-bc122fec7eb2/nuget/v3/flat2/microsoft.visualstudio.imaging.interop.14.0.designtime/16.11.31527.49/microsoft.visualstudio.imaging.interop.14.0.designtime.16.11.31527.49.nupkg'.
  Response status code does not indicate success: 503 (Service Unavailable).
/opt/hostedtoolcache/dotnet/sdk/5.0.400/NuGet.targets(131,5): error : Failed to download package 'Microsoft.VisualStudio.Imaging.Interop.14.0.DesignTime.16.11.31527.49' from 'https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/2a239fd0-3e21-40b0-b9d6-bc122fec7eb2/nuget/v3/flat2/microsoft.visualstudio.imaging.interop.14.0.designtime/16.11.31527.49/microsoft.visualstudio.imaging.interop.14.0.designtime.16.11.31527.49.nupkg'. [/home/vsts/work/1/s/Microsoft.VisualStudio.Threading.sln]
/opt/hostedtoolcache/dotnet/sdk/5.0.400/NuGet.targets(131,5): error : Response status code does not indicate success: 503 (Service Unavailable). [/home/vsts/work/1/s/Microsoft.VisualStudio.Threading.sln]
/opt/hostedtoolcache/dotnet/sdk/5.0.400/NuGet.targets(131,5): error : The feed 'vssdk-public [https://pkgs.dev.azure.com/azure-public/vside/_packaging/vssdk/nuget/v3/index.json]' lists package 'Microsoft.VisualStudio.Imaging.Interop.14.0.DesignTime.16.11.31527.49' but multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the current operation was in progress. Verify the package exists on the feed and try again. [/home/vsts/work/1/s/Microsoft.VisualStudio.Threading.sln]
/opt/hostedtoolcache/dotnet/sdk/5.0.400/NuGet.targets(131,5): error :   Unable to find package 'Microsoft.VisualStudio.Imaging.Interop.14.0.DesignTime.16.11.31527.49'. [/home/vsts/work/1/s/Microsoft.VisualStudio.Threading.sln]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Write-Error: /home/vsts/work/_temp/dd9bf25a-9219-4cad-be91-161af7b85855.ps1:3
Line |
   3 |  .\init.ps1 -AccessToken $AccessToken  -UpgradePrerequisites
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Failure while restoring packages.

```
