### PR TITLE
Check the status of waitTask before assuming a lock was acquired

### LINKED ISSUE #521: AsyncSemaphore can let too many callers enter when requests are cancelled
#### Bug description

Thread 1 is canceled while waiting to enter the semaphore, but so soon after it asks for the semaphore that the waitTask is completed by the time we check it (before we yield). Thread 1 is now "in" the semaphore but isn't accounted as such. This immediately would let one more thread in concurrently. And when thread 1 exits the semaphore, it will release it, leading to the semaphore allowing 2 threads from then on.

This bug in AsyncSemaphore has been present since its original version (many years ago). But StreamJsonRpc 2.0 was the first version that was vulnerable to it (or at least, the first version that would catch it when it happened and throw an exception). Which could explain failures like this appearing in VS as early as 16.1. We'll get this fixed in vs-threading and patch 16.4 immediately, and 16.3 as soon as we can get it approved. The risk of the fix should be low. Although it is in a very low-level class used in many places, the effect of the change should be very constrained and exactly what we need.

#### Repro steps

Have a thread trying to enter the semaphore with a CancellationToken that another thread cancels at exactly the same time. The cancellation has to take effect at a very narrow race condition between when *we* check for cancellation and when the SemaphoreSlim.EnterAsync method checks.

#### Expected behavior

Cancellation should be handled without allowing the caller to think they entered the semaphore.

#### Actual behavior

The caller is told they have entered the semaphore. But they haven't, so another thread may be allowed in immediately as well. When the canceled request *exits* the semaphore, the release the semaphore that they never really entered. This leads to the semaphore's AvailableCount being incremented by one. In a semaphore created with an initialCount of 1, this means that it will become a semaphore with 2 slots. From then on, too many will be allowed in.

- Version used: 16.3. But this bug impacts all previous versions.

### PR DESCRIPTION
**Pull request by sharwell**
Fixes a failure in AsyncSemaphore where cancellation during the call EnterAsync can lead to an incorrectly-claimed semaphore. When the Releaser later releases the semaphore, the semaphore transitions to a state where more than one thread may be allowed to use the semaphore.

Thread 1:
* Cancellation is triggered during the SemaphoreSlim.WaitAsync, which completes synchronously even though the semaphore was not acquired

Thread 2:
* Successfully acquires the semaphore

Thread 1:
* Throws an exception for cancellationToken.ThrowIfCancellationRequested()
* Releases the semaphore when exiting the using block

Thread 3:
* Successfully acquires the semaphore, even though Thread 2 has not released it

Fixes #521

### CODE REVIEW

File: src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs [hunk 1]
```diff
@@ -149,25 +149,34 @@ private Task<Releaser> LockWaitingHelper(Task waitTask)
         {
             Requires.NotNull(waitTask, nameof(waitTask));
 
-            return waitTask.IsCompleted
```
Comment (stephentoub) [inline src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs]: Seems like it could also be addressed by using IsCompletedSuccessfully instead of IsCompleted.  But what you changed it to is fine as well.

File: src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs [hunk 2]
```diff
@@ -149,25 +149,34 @@ private Task<Releaser> LockWaitingHelper(Task waitTask)
...
+                                throw new ObjectDisposedException(this.GetType().FullName);
+                            }
+
+                            return new Releaser((AsyncSemaphore)state);
+                        },
+                        this,
+                        CancellationToken.None,
+                        TaskContinuationOptions.ExecuteSynchronously,
+                        TaskScheduler.Default);
+            }
```
Comment (stephentoub) [inline src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs]: Alternatively, this could just be an async method:
```C#
private async Task<Releaser> LockWaitingHelper(Task waitTask)
{
    await waitTask.ConfigureAwait(false);
    if (this.disposed) throw new ObjectDisposedException(GetType().FullName);
    return new Releaser(this);
}
```

Comment (AArnott) [reply src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs]: True. We were trying to reduce allocations in the uncontested case by returning a saved task.

File: src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs (hunk 1 above)
Comment (AArnott) [reply src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs]: That's not available in net472 or netstandard2.0 which is what we target today.

Comment (stephentoub) [reply src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs]: In that case `waitTask.IsCompleted` => `waitTask.Status == TaskStatus.RanToCompletion`.  Again, what's here is fine, it's just adding a bit more code to optimize the canceled case.

File: src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs (hunk 2 above)
Comment (stephentoub) [reply src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs]: Fair enough.

Comment (sharwell) [reply src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs]: I agree that the current form is visually suboptimal, especially for the case of an exception thrown in the continuation (if even possible). However, I was trying to keep the fix as close to the current code flow as possible since we're taking it through servicing.

Comment (stephentoub) [reply src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs]: > I was trying to keep the fix as close to the current code flow as possible

If your goal is to keep the change as minimal as possible, wouldn't it just be a one-line change from:
```C#
return waitTask.IsCompleted
```
to:
```C#
return waitTask.Status == TaskStatus.RanToCompletion
```
?

Comment (sharwell) [reply src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs]: I believe it would leave the returned task in a faulted state instead of a cancelled state. I would be happy with that change though since technically it's already possible today.

File: src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs [hunk 3]
```diff
@@ -149,25 +149,34 @@ private Task<Releaser> LockWaitingHelper(Task waitTask)
...
-
-                        if (this.disposed)
+            switch (waitTask.Status)
+            {
+                case TaskStatus.RanToCompletion:
+                    // uncontested lock
+                    return this.uncontestedReleaser;
+
+                case TaskStatus.Canceled:
+                    return this.canceledReleaser;
```
Comment (sharwell) [inline src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs]: @AArnott Should we update this line to preserve the cancellation token in the cancelled task, similar to what we do in the caller?

File: src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs (hunk 2 above)
Comment (stephentoub) [reply src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs]: > I believe it would leave the returned task in a faulted state instead of a cancelled state

It would, but as you say, that's not the issue that's being fixed here.

File: src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs (hunk 3 above)
Comment (AArnott) [reply src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs]: I wouldn't normally care too much about that, but HeeJae has repeatedly called out places where he checks `OperationCanceledException.CancellationToken` so I guess people care about that sort of thing. But not in this particular fix, since the other method already does just this as well.

File: src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs (hunk 2 above)
Comment (AArnott) [reply src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs]: And the faulted task still throws the same exception. So that seems like a good way to minimize the diff.

File: src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs (hunk 1 above)
Comment (AArnott) [reply src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs]: And the faulted task still throws the same exception. So that seems like a good way to minimize the diff.

Comment (sharwell) [reply src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs]: PR is now updated using the simpler form 👍

File: src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs (hunk 2 above)
Comment (sharwell) [reply src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs]: Now updated to the simpler form 👍

File: src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs [hunk 4]
```diff
@@ -179,7 +179,7 @@ private Task<Releaser> LockWaitingHelper(Task<bool> waitTask)
         {
             Requires.NotNull(waitTask, nameof(waitTask));
 
-            return waitTask.IsCompleted
+            return waitTask.Status == TaskStatus.RanToCompletion
```
Comment (AArnott) [inline src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs]: This change isn't necessary. We already call `waitTask.Result` which will throw instead of returning the `uncontestedReleaser` so it's unrelated to this bug.

Comment (sharwell) [reply src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs]: Reverted this one. It's still a bug, but not as severe and can be implemented separately with its own test.

**Comment by AArnott** [comment]
QB approved
